# GitHub Action for Yii Framework with PostgreSQL
name: Testing Yii2 with PostgreSQL
on: [push, pull_request]
jobs:
  yii:
    name: Yii2 (PHP ${{ matrix.php-versions }})
    runs-on: ubuntu-latest
    env:
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      TEST_DB_USERNAME: postgres
      TEST_DB_PASSWORD: postgres
      DB_CHARSET: utf8

    # Docs: https://docs.github.com/en/actions/using-containerized-services
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 3
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      # Docs: https://github.com/shivammathur/setup-php
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl, gd, imagick, zip, dom, pgsql
          coverage: xdebug
          tools: cs2pr, phpcs

      # Local PostgreSQL service in GitHub hosted environments is disabled by default.
      # If you are using it instead of service containers, make sure you start it.
      # - name: Start postgresql service
      #   run: sudo systemctl start postgresql.service

      - name: Get composer cache directory
        id: composer-cache
        working-directory: ./project/src/
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

      - name: Cache composer dependencies
        uses: actions/cache@v3
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          # Use composer.json for key, if composer.lock is not committed.
          # key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.json') }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-

      - name: Install Composer dependencies
        working-directory: ./project/src/
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Prepare the application
        working-directory: ./project/src/
        run: |
          php -r "file_exists('.env') || copy('.env.dist', '.env');"
        env:
          DB_DSN: pgsql:host=127.0.0.1;port=${{ job.services.postgres.ports['5432'] }};dbname=postgres
          TEST_DB_DSN: pgsql:host=127.0.0.1;port=${{ job.services.postgres.ports['5432'] }};dbname=postgres

      - name: Run Tests
        working-directory: ./project/src/
        run: |
          vendor/bin/codecept build
          nohup php -S localhost:8080 > yii.log 2>&1 &
          vendor/bin/codecept run --coverage-xml
          vendor/bin/php-coveralls -v
        env:
          DB_DSN: pgsql:host=127.0.0.1;port=${{ job.services.postgres.ports['5432'] }};dbname=postgres
          TEST_DB_DSN: pgsql:host=127.0.0.1;port=${{ job.services.postgres.ports['5432'] }};dbname=postgres
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Run phpcs
        working-directory: ./project/src/
        run: phpcs --standard=PSR12 -q --report=checkstyle ./controllers/ | cs2pr
        
      #- name: Upload coverage results to Coveralls
      #  env:
      #    COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #  run: |
      #    composer global require php-coveralls/php-coveralls
      #    vendor/bin/php-coveralls
      #    php-coveralls --coverage_clover=build/logs/clover.xml -v
      
      #- name: Send coverage report to Coveralls for Active LTS version
      #  uses: coverallsapp/github-action@master
      #  with:
      #    github-token: ${{ secrets.GITHUB_TOKEN }}

  all_tests:
    name: Tests For All Versions Successful
    needs: [yii]
    runs-on: ubuntu-latest
    steps:
      - name: Return Status
        run: true
